apiVersion: v1
kind: Service
metadata:
  name: service-microservice
spec:
  type: NodePort
  selector:
    app: microservice
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
